kind: Service
apiVersion: v1
metadata:
  name: helidon-examples-employee-app
  labels:
    app: helidon-examples-employee-app
spec:
  type: NodePort
  selector:
    app: helidon-examples-employee-app
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helidon-examples-employee-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helidon-examples-employee-app
        version: v1
    spec:
      containers:
        - name: helidon-examples-employee-app
          image: helidon-examples-employee-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: helidon-examples-employee-app
  labels:
    app: helidon-examples-employee-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: helidon-examples-employee-app
                                
                            